name: "Setup Node.js Environment"
description: "Setup Node.js with caching and version from .nvmrc"

inputs:
  node-version:
    description: "Node.js version to use (defaults to .nvmrc)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Read .nvmrc
      id: nvmrc
      shell: bash
      run: |
        if [ -f .nvmrc ]; then
          echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        else
          echo "node_version=20" >> $GITHUB_OUTPUT
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version || steps.nvmrc.outputs.node_version }}
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: npm ci
