name: "Checkout Repository"
description: "Checkout repository with proper configuration"

inputs:
  ref:
    description: "Branch, tag or SHA to checkout"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: 0
